/* V9.3.6 — Digital Factory offline app-shell cache. */
const VU_SW_BUILD='9.3.6';
const CACHE=`vu-app-${VU_SW_BUILD}`;
const PRECACHE=[
'./','./index.html','./manifest.webmanifest','./vorster-logo.jpg','./styles.css','./inventory.css','./completion-schedule.css','./job-card-matching.css','./production-workflow.css','./polish-v8.css','./ui-polish-v9.css',
'./runtime-guard.js','./db.js','./app.js','./inventory.js','./raw-stock-v8.js','./production-capacity.js','./order-line-classification-v8.js','./manufacturing-classification-v9.js','./operations-three-stage-v9.js','./strict-division-worksheets-v9.js','./division-daily-work-v9.js','./raw-production-unified-v9.js','./business-outcome-optimizer-v9.js','./manager-plan-priority-v9.js','./completion-schedule.js','./completion-schedule-optimizer-authority-v9.js','./order-progress-v9.js','./shared-data-v9.js','./shared-data-project-defaults-v9.js','./shared-data-bootstrap-fix-v9.js','./shared-data-batched-pull-v9.js','./shared-reconciliation-v9.js','./shared-refresh-v9.js','./painted-stock-inventory-authority-v9.js','./navigation-authority-v9.js','./dashboard-authority-v9.js','./daily-factory-pack-v9.js','./auto-fulfilment-planner-v9.js','./factory-pack-fulfilment-authority-v9.js','./runtime-integrity-v9.js','./ui-stability-v9.js','./build-version-v9.js','./production-set-delete-authority-v9.js','./painting-full-order-authority-v9.js','./order-update-recalc-authority-v9.js','./worksheet-paint-reconciliation-authority-v9.js','./order-identity-reconciliation-v9.js','./partial-dispatch-capture-v9.js','./dispatch-stepper-authority-v9.js','./live-factory-pack-authority-v9.js','./digital-factory-v93.js','./digital-factory-target-overrides-v93.js','./digital-factory-target-bridge-v93.js','./digital-factory-exceptions-v93.js','./digital-factory-role-shell-v93.js','./digital-factory-manager-dashboard-v93.js','./digital-factory-manager-control-v93.js','./digital-factory-manager-targets-v93.js','./digital-factory-manager-exceptions-v93.js','./manager-command-centre-v93.js'];
async function precache(){const cache=await caches.open(CACHE);await Promise.all(PRECACHE.map(async url=>{try{const r=await fetch(url,{cache:'no-store'});if(r.ok)await cache.put(url,r.clone())}catch{}}))}
self.addEventListener('install',e=>e.waitUntil((async()=>{await precache();await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;e.respondWith((async()=>{const c=await caches.open(CACHE);try{const f=await fetch(r,{cache:'no-store'});if(f.ok&&new URL(r.url).origin===self.location.origin)c.put(r,f.clone()).catch(()=>{});return f}catch{const x=await c.match(r);if(x)return x;if(r.mode==='navigate')return (await c.match('./index.html'))||(await c.match('./'));return Response.error()}})())});